### ISSUE TITLE
[Linux] Missing .so library files

### ISSUE THREAD

**Issue by HastagGuigui** [devdave/pybass3#2]
I was missing a file called "libbass.so", that I added in my project from the BASS linux download. However, after adding that file, I am now getting an error saying:
```
OSError: ./libbass.so: wrong ELF class: ELFCLASS32
```

I suspect I didn't get the correct BASS version, but then what version do I need?

**Comment by devdave** [comment]
I unfortunately didn't do much/any testing with Linux but the ELFCLASS32 error is a sign that the .so was compiled as 32 bit while the Python interpreter is 64bit.   In the bass24-linux zip file, try the libs/x86_64 libbass.so and if that doesn't work then the next culprit would be the Python interpreter running as 32 bit.

**Comment by HastagGuigui** [comment]
Found it!... Though, now the module tells me Linux support isn't available...

**Comment by devdave** [comment]
I am kind of surprised it needs tags and that's a mistake on my part.   Go back to Un4seen's website, go to the BASS library addons, and grab this library https://www.un4seen.com/download.php?z/3/tags18-linux you want `tags18-linux.zip\libs\x86_64\libtags.so` and rename it to `tags.so` but you might need to manually copy that into your python's `site-packages\pybass3\vendor` given how it imports the modules at https://github.com/devdave/pybass3/blob/master/src/pybass3/bass_tags.py#L15


What flavor of Linux are you running this on?  This upcoming Sunday evening I can boot that up on a USB chip and see what other stumbling points there might be.

**Comment by HastagGuigui** [comment]
I'm using Zorin OS on my laptop, and Pop!_OS on my desktop, both are Ubuntu-based.

**Comment by devdave** [comment]
Just a update, I am having a weird time getting Ubuntu to run on my work station but I haven't forgotten this issue and am still working on it.

**Comment by HastagGuigui** [comment]
alright alright, meanwhile im trying to import the `tags.so` into the module

**Comment by HastagGuigui** [comment]
Hey, it's been a while! Writing you because I managed to get it working. However, the only way I managed to make it work is by putting both `libbass.so` and `tags.so` in my project folder.

**Comment by devdave** [comment]
I am very glad to hear that you did get it working finally.   As soon as I get a linux workstation up and going it will  be a quick fix to embed the missing so library files in the pypi wheel/distro.   Do you mind if I leave this issue open until I make the appropriate fixes?

**Comment by HastagGuigui** [comment]
Sure thing! Lemme just rename the issue to a more appropriate name.

**Comment by HastagGuigui** [comment]
Hi! Just wanted to know if you managed to get a linux vm up and tried to fix it?
